---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://localhost"
    includePaths:
    - "http://localhost.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- alertFilters:
  - ruleId: 10021
    #ruleName: "X-Content-Type-Options Header Missing (10021)"
    context: "Default Context"
    newRisk: "False Positive"
    #parameter: ""
    #parameterRegex: false
    url: "http://localhost"
    urlRegex: true
    #attack: ""
    #attackRegex: false
    #evidence: ""
    #evidenceRegex: false
  #parameters:
  # deleteGlobalAlerts: false
  #name: "alertFilter"
  type: "alertFilter"
- parameters:
    maxAlertsPerRule: 0
    scanOnlyInScope: true
    maxBodySizeInBytesToScan: 0
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
  name: "spider"
  type: "spider"
- parameters:
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 16
    inScopeOnly: true
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
  name: "spiderAjax"
  type: "spiderAjax"
- parameters:
    maxDuration: 5
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    template: "traditional-html"
    reportDir: "/Users/nqi/docker-simple-webserver"
    reportFile: "report.html"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
    displayReport: true
  risks:
  - "info"
  - "low"
  - "medium"
  - "high"
  confidences:
  - "falsepositive"
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  name: "report"
  type: "report"

